Enhanced Parallel Processing and Plotting in ELMPostprocessR
walkeranthonyp/ELM_postprocessR pull request #1
Opened 2024-05-07 20:34 UTC by sharma-bharat

With this latest update, ELMPostprocessR now supports parallel execution for both processing and plotting the ensemble members of simulation outputs independently.

2024-05-07 20:37 UTC, sharma-bharat commented
Examples of bash scripts to run ELM_postprocessR on single and ensemble runs.

[postprocessR_singleFACE.txt](https://github.com/walkeranthonyp/ELM_postprocessR/files/15240732/postprocessR_singleFACE.txt)
[postprocessR_ensembleFACE_parallel.txt](https://github.com/walkeranthonyp/ELM_postprocessR/files/15240733/postprocessR_ensembleFACE_parallel.txt)

2024-05-16 13:36 UTC, walkeranthonyp requested changes

2024-05-16 13:36 UTC, walkeranthonyp commented on functions_plotting.R
> +    print ("BS...>>>")
Please remove these "BS" tags

2024-05-16 13:36 UTC, walkeranthonyp commented on plot_ELM.R
> +  uq              <- NULL
Please align the "<-" with above

2024-05-16 13:36 UTC, walkeranthonyp commented on plot_ELM.R
> +}
Please indent the print line by 2 columns, or make if all one line

2024-05-16 13:36 UTC, walkeranthonyp commented on plot_ELM.R
> +    fname   <- paste(caseidprefix,sites,case_labs[c],sep='_')
Please align all of the "<-" to the same column and make sure they're followed by a single space

2024-05-16 13:36 UTC, walkeranthonyp commented on process_ELM_output.R
> -# April 2021
Please retain the initial date (April 2021)

2024-05-16 13:36 UTC, walkeranthonyp commented on process_ELM_output.R
> +uq_index    <- NULL
align <-

2024-05-16 13:36 UTC, walkeranthonyp commented on process_ELM_output.R
> +    # ... `uq_index` is the index/id of the ensemble run
please change "run" to "member" in this comment

2024-05-16 13:36 UTC, walkeranthonyp commented on process_ELM_output.R
> +    # ... `uq` is the number of ensembles
I think you mean number of ensemble members

2024-05-16 13:36 UTC, walkeranthonyp commented on process_ELM_output.R
> +    print(uq_index)
Please combine these print statements

2024-05-22 15:05 UTC, sharma-bharat commented
I have made the changes based on your comments. Please review them!

2024-05-22 15:25 UTC, walkeranthonyp approved these changes
Thanks!

2024-05-22 15:25 UTC, merged